andeco/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('apps.inicio.urls')),
    url(r'^', include('apps.finanzas.urls')),
    url(r'^', include('apps.juridica.urls')),
    url(r'^', include('apps.municipios.urls')),
    url(r'^', include('apps.Planificacion.urls')),

]

apps/inicio/urls.py
from django.conf.urls import patterns, url
from.views import Index, loginview, Inicio, UserCreate

urlpatterns = patterns('',
	url(r'^$', Index.as_view(), name='index'),
    url(r'^inicio/$', Inicio.as_view(), name='inicio'),
	url(r'^salir/$', 'apps.inicio.views.logOut'),
	url(r'^login/$', loginview.as_view(), name='login'),
	url(r'^user_create/$', 'apps.inicio.views.UserCreate', name='user_create'),
	url(r'^lista_usuarios/$', 'apps.inicio.views.ListaUsuarios', name='lista_usuarios'),
	url(r'^delete_usuario/(?P<id>\d+)$', 'apps.inicio.views.eliminarUsuario', name='delete_usuario'),
  	url(r'^editar_user/(?P<pk>\d+)$', 'apps.inicio.views.user_edit', name='editar_user'),
  	url(r'^editar_user/(?P<pk>\d+)/password$', 'apps.inicio.views.change_password', name='user_password'),

	)

apps/inicio/forms.py
# -*- coding: utf-8 -*-
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django import forms
from apps.users.models import User


class LoginForm(AuthenticationForm):
    pass


# class Userform(UserCreationForm):
#     CHOICES = (
#         ('', 'selecciona'),
#         ('Admin', 'Administrador'),
#         ('Supervisor', 'Supervisor'),
     
#     )
#     roles = forms.ChoiceField(choices=CHOICES, required=True, label='Rol')

list_of_choices = (
    ('', 'selecciona'),
    ('AdminSistema', 'Administrador Sistema'),
    ('Admin', 'Administrador'),
    ('JefeArea', 'Jefe Area'),
    ('Supervisor', 'Supervisor'),
)

list_of_edit = (
    ('', 'selecciona'),
    ('admin_sistema', 'Administrador Sistema'),
    ('admin', 'Administrador'),
    ('jefe_area', 'Jefe Area'),
    ('supervisor', 'Supervisor'),
)

list_of_area = (
    ('', 'selecciona'),
    ('Planificacion', 'Planificacion'),
    ('Finanzas', 'Finanzas'),
    ('Juridica', 'Juridica'),
)


class UserForm(forms.ModelForm):
    nombre = forms.CharField(label="Nombre")
    p_apellido = forms.CharField(label="Primer apellido")
    s_apellido = forms.CharField(required=False, label="Segundo apellido")
    password = forms.CharField(widget=forms.PasswordInput(), label="Contraseña")
    password2 = forms.CharField(widget=forms.PasswordInput(attrs=dict(max_length=30, render_value=False)), label="Contraseña (confirmación):")
    roles = forms.ChoiceField(choices=list_of_choices)
    area = forms.ChoiceField(required=False, choices=list_of_area)

    class Meta:
        model = User
        fields = ('nombre', 'p_apellido', 'area', 's_apellido', 'username', 'password')

    def clean_username(self): # check if username dos not exist before
        try:
            User.objects.get(username=self.cleaned_data['username']) #get user from user model
        except User.DoesNotExist:
            return self.cleaned_data['username']

        raise forms.ValidationError("este usuario ya existe")

    def clean(self):
        if 'password' in self.cleaned_data and 'password2' in self.cleaned_data:
            if self.cleaned_data['password'] != self.cleaned_data['password2']:
                raise forms.ValidationError("Los dos campos de contraseña no coinciden.")
        return self.cleaned_data


class UserFormedit(forms.ModelForm):
    nombre = forms.CharField(label="Nombre")
    p_apellido = forms.CharField(label="Primer apellido")
    s_apellido = forms.CharField(required=False, label="Segundo apellido")
    roles = forms.ChoiceField(choices=list_of_edit)
    area = forms.ChoiceField(required=False, choices=list_of_area)

    class Meta:
        model = User
        fields = ('nombre', 'p_apellido', 's_apellido', 'username')


class reset_form(forms.Form):
    newpassword1 = forms.CharField(max_length=20, label="Contraseña", widget=forms.TextInput(attrs={'type':'password',  'class' : 'span'}))
    newpassword2 = forms.CharField(max_length=20, label="Contraseña (de nuevo)", widget=forms.TextInput(attrs={'type':'password',  'class' : 'span'}))

    def clean(self):
        if 'newpassword1' in self.cleaned_data and 'newpassword2' in self.cleaned_data:
            if self.cleaned_data['newpassword1'] != self.cleaned_data['newpassword2']:
                raise forms.ValidationError("Los dos campos de contraseña no coinciden.")
        return self.cleaned_data

apps/inicio/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect, render_to_response, get_object_or_404
from django.views.generic import FormView, View, TemplateView
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.core.urlresolvers import reverse_lazy
from .forms import LoginForm, UserForm, UserFormedit, reset_form
# PARA ASIGNAR USUARIOS A ROLES
from apps.users.models import User
from apps.inicio.roles import *
from django.template import RequestContext


class Index(View):
	def get(self, request, *args, **kwargs):

		if not request.user.is_authenticated():
			return HttpResponseRedirect(reverse_lazy('login'))
		else:
			return HttpResponseRedirect(reverse_lazy('inicio'))


class Inicio(TemplateView):
	template_name = 'inicio/index.html'

	@method_decorator(login_required)
	def dispatch(self, *args, **kwargs):
		return super(Inicio, self).dispatch(*args, **kwargs)


class loginview(FormView):

    form_class = LoginForm
    template_name = 'inicio/login.html'
    success_url = reverse_lazy("inicio")

    def form_valid(self, form): 
    	login(self.request, form.get_user())
        return super(loginview, self).form_valid(form)


def eliminarUsuario(request, id):
    u = User.objects.get(id=id)
    u.delete()
    return HttpResponseRedirect(reverse_lazy('lista_usuarios'))
# esto es lo que me esta hacindo no lo pongas

# class UserCreate(FormView):
#     form_class = UserForm
#     template_name = 'inicio/user_register.html'
#     success_url = reverse_lazy('lista_usuarios')

#     def form_valid(self, form):
#         user = form.save()
#         roles = form.cleaned_data['roles']
#         userGet = User.objects.get(id=user.id)

#         if roles == 'Admin':
#             Admin.assign_role_to_user(userGet)

#         if roles == 'Supervisor':
#             Operador.assign_role_to_user(userGet)

#         return super(UserCreate, self).form_valid(form)


def UserCreate(request):
    context = RequestContext(request)

    if request.method == 'POST':

        user_form = UserForm(request.POST)

        # If the two forms are valid...
        if user_form.is_valid():
            # Save the user's form data to the database.
            print 'validooooo'
            user = user_form.save()
            # user.empresa = user_form.cleaned_data['empresa']
            user.set_password(user.password)
            user.save()

            rol = user_form.cleaned_data['roles']

            if rol == 'AdminSistema':
                AdminSistema.assign_role_to_user(user)

            if rol == 'Admin':
                Admin.assign_role_to_user(user)

            if rol == 'JefeArea':
                JefeArea.assign_role_to_user(user)

            if rol == 'Supervisor':
                Supervisor.assign_role_to_user(user)

            return HttpResponseRedirect(reverse_lazy('lista_usuarios'))

        else:
            print user_form.errors
    else:
        user_form = UserForm()

    return render_to_response('inicio/user_register.html', {'user_form': user_form}, context)


def logOut(request):
	logout(request)
	return redirect('/')


def ListaUsuarios(request):
    users = User.objects.filter(is_staff=False)
    variables = RequestContext(request, {'usuarios': users})

    return render_to_response('inicio/listado_usuarios.html', variables)


def user_edit(request, pk):
        user = get_object_or_404(User, pk=pk)
        form = UserFormedit()

        if request.method == "POST":

            form = UserFormedit(request.POST, instance=user)
            if form.is_valid():
                user = form.save(commit=False)
                # post.author = request.user
                user.save()

                rol = form.cleaned_data['roles']

                if rol == 'admin_sistema':
                    AdminSistema.assign_role_to_user(user)

                if rol == 'admin':
                    Admin.assign_role_to_user(user)

                if rol == 'jefe_area':
                    JefeArea.assign_role_to_user(user)

                if rol == 'supervisor':
                    Supervisor.assign_role_to_user(user)

                return HttpResponseRedirect(reverse_lazy('lista_usuarios'))

        return render(request, 'inicio/update.html', {'user_form': form, 'usere': user})


def change_password(request, pk):
    user = get_object_or_404(User, pk=pk)
    if request.method == 'POST':
        form = reset_form(request.POST)
        if form.is_valid():
            newpassword = form.cleaned_data['newpassword1']
            user.set_password(newpassword)
            user.save()
            return HttpResponseRedirect(reverse_lazy('lista_usuarios'))

    else:
        form = reset_form()
    content = RequestContext(request, {'form': form, 'user_data': user})
    return render(request, 'inicio/reset_password.html', content,)

templates/inicio/index.html
{% extends "base.html" %}
{% block contenido %}
	        <!-- page content -->
        <div class="right_col" role="main">
          <div class="">
            <div class="row top_tiles">
              <div class="animated flipInY col-lg-4 col-md-4 col-sm-6 col-xs-12">
                <div class="tile-stats">
                  <div class="icon"><i class="fa fa-caret-square-o-right"></i></div>
                  <div class="count">Finanzas</div>
                  <h3>New Sign ups</h3>
                  <p>Lorem ipsum psdea itgum rixt.</p>
                </div>
              </div>
              <div class="animated flipInY col-lg-4 col-md-4 col-sm-6 col-xs-12">
                <div class="tile-stats">
                  <div class="icon"><i class="fa fa-comments-o"></i></div>
                  <div class="count">Planificacion</div>
                  <h3>New Sign ups</h3>
                  <p>Lorem ipsum psdea itgum rixt.</p>
                </div>
              </div>
             
              <div class="animated flipInY col-lg-4 col-md-4 col-sm-6 col-xs-12">
                <div class="tile-stats">
                  <div class="icon"><i class="fa fa-check-square-o"></i></div>
                  <div class="count">Juridica</div>
                  <h3>New Sign ups</h3>
                  <p>Lorem ipsum psdea itgum rixt.</p>
                </div>
              </div>
            </div>



         


          </div>
        </div>
        <!-- /page content -->
{% endblock contenido %}  

templates/inicio/listado_usuarios.html
{% extends "base.html" %}
{% block contenido %}
{% load permission_tags %}
  <!-- page content -->
        <div class="right_col" role="main">
          <div class="">
            <div class="page-title">
              
             
            </div>

            <div class="clearfix"></div>

            <div class="row">

              <div class="col-md-12 col-sm-12 col-xs-12">
           
              <a href="/user_create" class="btn btn-success">Crear Usuario</a>
             
             

                <div class="x_panel">
                  
                    
                  <div class="x_content">
                    <div class="table-responsive"> 
                      <table id="" class="table table-striped table-bordered jambo_table mediaTable" cellspacing="0" width="100%">
                        <thead>
                          <tr>
                           
                            <th class="essential persist">N°</th>
                            <th class="oculto">Usuario</th>
                            <th>Rol</th>
                            <th>Area</th>
                            
                            <th class="essential persist"></th>
                           
                          </tr>
                        </thead>

                        <tbody>
                          
                          {% for u in usuarios %}
                              <tr>
                                <td>{{forloop.counter}}</td>
                               
                                <td>{{ u.username}}</td>
                                <td>
                                  {% if u|has_role:'admin_sistema' %}
                                    Administrador sistema
                                  {% endif %}
                                  {% if u|has_role:'admin' %}
                                    Administrador
                                  {% endif %}
                                  {% if u|has_role:'jefe_area' %}
                                    Jefe de area
                                  {% endif %}
                                  {% if u|has_role:'supervisor' %}
                                    Supervisor
                                  {% endif %}
                                </td>
                                <td>

                                  {% if u.area %}
                                    {{u.area}}
                                  {% else %}
                                    -----------------
                                  {% endif %}

                                </td>
                                 
                                <td>
                                  <a href="/editar_user/{{u.pk}}" class="btn btn-warning btn-sm" data-toggle="tooltip" data-original-title="Editar" ><i class="fa fa-pencil"></i></a>
                              
                                  
                                  
                                  <a  class="btn btn-danger btn-sm" data-toggle="modal" data-original-title="Eliminar"  data-target=".modal-{{ u.pk}}"><i class="fa fa-trash-o"></i> </a>

                                  <div class="modal fade modal-{{ u.pk}}" tabindex="-1" role="dialog" aria-hidden="true" style="display: none;">
                                    <div class="modal-dialog modal-lg">
                                      <div class="modal-content">

                                        <div class="modal-header">
                                          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span>
                                          </button>
                                          <h4 class="modal-title" id="myModalLabel2">Eliminar</h4>
                                        </div>
                                        <div class="modal-body">
                                          Esta seguro que  quiere eliminar "{{ u.username}}"
                                        </div>
                                        <div class="modal-footer">
                                          <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                                        
                                          <a href="/delete_usuario/{{u.pk}}" class="btn btn-primary">Aceptar</a>
                                        </div>
                                      </div>
                                    </div>
                                  </div>
                                 
                                </td>

                                
                              </tr>

                          {% endfor %}
                          
                     
                          
                        </tbody>
                      </table>
                    </div>
                  </div>
              
              </div>

            </div>
          </div>
        </div>
        <!-- /page content -->
{% endblock %}
{% block js %}
  <script>
  
  </script>
{% endblock js %}

templates/inicio/reset_password.html
{% extends "base.html" %}
{% block contenido %}
{% load widget_tweaks %}


<div class="right_col" role="main">
          <div class="">
            <div class="page-title">
              <div class="title_left">
                <h3>Cambiar contraseña</h3>
              </div>         
            </div>
            <div class="clearfix"></div>
            <div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <span>Introduzca una nueva contraseña para el usuario </span><b>{{user_data.username}}</b>
                  {% if form.non_field_errors%}
                    <div class="alert alert-danger alert-dismissible fade in" role="alert">
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span>
                      </button>
                      <strong>{{form.non_field_errors|removetags:"ul li"}}</strong>
                    </div>
                  {% endif %}

                  <div class="x_content">
                  
                    <br />
                    <form id="demo-form2"  class="form-horizontal form-label-left" method="post" novalidate="" data-parsley-validate="">
						        {% csrf_token %}
                      
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">{{ form.newpassword1.label }}<span class="required"></span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          {{form.newpassword1|add_class:"form-control col-md-7 col-xs-12"|add_error_class:"parsley-error"|attr:"required:required"}}
                          {% if form.errors.newpassword1 %}
                            <ul id="parsley-id-5" class="parsley-errors-list filled">
                              <li class="parsley-required">{{form.errors.newpassword1|removetags:'ul li'}}</li>
                            </ul>
                         {% endif %}

                        </div>
                      </div>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">{{ form.newpassword2.label }}<span class="required"></span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          {{form.newpassword2|add_class:"form-control col-md-7 col-xs-12"|add_error_class:"parsley-error"|attr:"required:required"}}
                          {% if form.errors.newpassword2 %}
                            <ul id="parsley-id-5" class="parsley-errors-list filled">
                              <li class="parsley-required">{{form.errors.newpassword2|removetags:'ul li'}}</li>
                            </ul>
                         {% endif %}

                        </div>
                      </div>

                   
                      <div class="ln_solid"></div>
                      <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                          <button type="submit" class="btn btn-primary">Cancelar</button>
                          <button type="submit" class="btn btn-success">Guardar</button>
                        </div>
                      </div>

                    </form>
                  </div>
                </div>
              </div>
            </div>


           
          </div>
        </div>


{% endblock %}
{% block js %}
	<script>
      $('.area').hide();
      $('#id_roles').on('change', function() {
        console.log( this.value );
        if (this.value == 'JefeArea' || this.value == 'Supervisor') {
          $('.area').show();
          $('#id_area').attr('required', 'required');
        }else{
          $('.area').hide();
          $("#id_area").removeAttr("required");
        }
      })


      // initialize the validator function
      validator.message.date = 'not a real date';

      // validate a field on "blur" event, a 'select' on 'change' event & a '.reuired' classed multifield on 'keyup':
      $('form')
        .on('blur', 'input[required], input.optional, select.required', validator.checkField)
        .on('change', 'select.required', validator.checkField)
        .on('keypress', 'input[required][pattern]', validator.keypress);

      $('.multi.required').on('keyup blur', 'input', function() {
        validator.checkField.apply($(this).siblings().last()[0]);
      });

      $('form').submit(function(e) {
        e.preventDefault();
        var submit = true;

        // evaluate the form using generic validaing
        if (!validator.checkAll($(this))) {
          submit = false;
        }

        if (submit)
          this.submit();

        return false;
      });




    </script>
{% endblock js %}

templates/inicio/update.html
{% extends "base.html" %}
{% block contenido %}
{% load widget_tweaks %}


<div class="right_col" role="main">
          <div class="">
            <div class="page-title">
              <div class="title_left">
                <h3>Registro Usuario</h3>
              </div>         
            </div>
            <div class="clearfix"></div>
            <div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                
                  <div class="x_content">
                    <br />
                    <form id="demo-form2"  class="form-horizontal form-label-left" method="post" novalidate="" data-parsley-validate="">
						        {% csrf_token %}
                     <fieldset>
                      <legend>Datos personales</legend>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Nombre<span class="required"></span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          <input class="form-control col-md-7 col-xs-12 {% if user_form.errors.nombre %} parsley-error {%endif%}" id="id_nombre" name="nombre" required="required" type="text" value="{{usere.nombre}}">
                          {% if user_form.errors.nombre %}
                            <ul id="parsley-id-5" class="parsley-errors-list filled">
                              <li class="parsley-required">{{user_form.errors.nombre|removetags:'ul li'}}</li>
                            </ul>
                         {% endif %}

                        </div>
                      </div>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Primer apellido<span class="required"></span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
            
                          <input class="form-control col-md-7 col-xs-12 {% if user_form.errors.p_apellido %} parsley-error {%endif%}" id="id_p_apellido" name="p_apellido" required="required" type="text" value="{{usere.p_apellido}}">
                          {% if user_form.errors.p_apellido %}
                            <ul id="parsley-id-5" class="parsley-errors-list filled">
                              <li class="parsley-required">{{user_form.errors.p_apellido|removetags:'ul li'}}</li>
                            </ul>
                         {% endif %}

                        </div>
                      </div>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Segundo apellido<span class="required"></span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          <input class="form-control col-md-7 col-xs-12 {% if user_form.errors.s_apellido %} parsley-error {%endif%}" id="id_s_apellido" name="s_apellido" type="text" value="{{usere.s_apellido}}">
                          {% if user_form.errors.s_apellido %}
                            <ul id="parsley-id-5" class="parsley-errors-list filled">
                              <li class="parsley-required">{{user_form.errors.s_apellido|removetags:'ul li'}}</li>
                            </ul>
                         {% endif %}

                        </div>
                      </div>
                    </fieldset>
                    <fieldset>
                    <legend>Datos de usuario</legend>
						         
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Usuario<span class="required"></span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          <input class="form-control col-md-7 col-xs-12 {% if user_form.errors.username %} parsley-error {%endif%}" id="id_username" maxlength="100" name="username" required="required" type="text" value="{{usere.username}}">
                          {% if user_form.errors.username %}
                            <ul id="parsley-id-5" class="parsley-errors-list filled">
                              <li class="parsley-required">{{user_form.errors.username|removetags:'ul li'}}</li>
                            </ul>
                         {% endif %}

                        </div>
                      </div>

                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Contraseña<span class="required"></span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          
                          <a href="/editar_user/{{usere.pk}}/password" class="btn btn-warning" ><i class="fa fa-lock"></i> Cambiar contraseña</a>

                        </div>
                      </div>

                     

                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Rol <span class="required"></span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          {{user_form.roles|add_class:"form-control col-md-7 col-xs-12"|add_error_class:"parsley-error"|attr:"required:required"}}
                          {% if user_form.errors.roles %}
                            <ul id="parsley-id-5" class="parsley-errors-list filled">
                              <li class="parsley-required">{{user_form.errors.roles|removetags:'ul li'}}</li>
                            </ul>
                         {% endif %}

                        </div>
                      </div>

                       <div class="form-group area">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Area <span class="required"></span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          {{user_form.area|add_class:"form-control col-md-7 col-xs-12"|add_error_class:"parsley-error"}}
                          {% if user_form.errors.area %}
                            <ul id="parsley-id-5" class="parsley-errors-list filled">
                              <li class="parsley-required">{{user_form.errors.area|removetags:'ul li'}}</li>
                            </ul>
                         {% endif %}

                        </div>
                      </div>
                    </fieldset>

                     

                      

                      

                      <div class="ln_solid"></div>
                      <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                          <button type="submit" class="btn btn-primary">Cancelar</button>
                          <button type="submit" class="btn btn-success">Guardar</button>
                        </div>
                      </div>

                    </form>
                  </div>
                </div>
              </div>
            </div>


           
          </div>
        </div>


{% endblock %}
{% block js %}
	<script>
      $('.area').hide();
      $('#id_roles').on('change', function() {
        console.log( this.value );
        if (this.value == 'jefe_area' || this.value == 'supervisor') {
          $('.area').show();
          $('#id_area').attr('required', 'required');
        }else{
          $('.area').hide();
          $("#id_area").removeAttr("required");
        }
      });

      $('#id_roles option:selected').removeAttr("selected");
      {% for group in usere.groups.all %}
          
        $('#id_roles option[value="{{group.name}}"]').attr("selected","selected");
      {% endfor %}

      {% if usere.area %}
        $('.area').show();
        $('#id_area option:selected').removeAttr("selected");
        $('#id_area option[value="{{usere.area}}"]').attr("selected","selected");
        $('#id_area').attr('required', 'required');
      {% endif %}


      // initialize the validator function
      validator.message.date = 'not a real date';

      // validate a field on "blur" event, a 'select' on 'change' event & a '.reuired' classed multifield on 'keyup':
      $('form')
        .on('blur', 'input[required], input.optional, select.required', validator.checkField)
        .on('change', 'select.required', validator.checkField)
        .on('keypress', 'input[required][pattern]', validator.keypress);

      $('.multi.required').on('keyup blur', 'input', function() {
        validator.checkField.apply($(this).siblings().last()[0]);
      });

      $('form').submit(function(e) {
        e.preventDefault();
        var submit = true;

        // evaluate the form using generic validaing
        if (!validator.checkAll($(this))) {
          submit = false;
        }

        if (submit)
          this.submit();

        return false;
      });




    </script>
{% endblock js %}