andeco/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('apps.inicio.urls')),
    url(r'^', include('apps.finanzas.urls')),
    url(r'^', include('apps.juridica.urls')),
    url(r'^', include('apps.municipios.urls')),
    url(r'^', include('apps.Planificacion.urls')),

]

apps/municipios/urls.py
from django.conf.urls import patterns, url
from .views import municipios, Crearmunicipios, Crearprovincias, provincias

urlpatterns = patterns('',
    url(r'^municipios/$', municipios.as_view(), name='municipios'),
    url(r'^crear_municipio/$', Crearmunicipios.as_view(), name='crear_municipio'),
    url(r'^provincia/$', provincias.as_view(), name='provincia'),
    url(r'^crear_provincia/$', Crearprovincias.as_view(), name='crear_provincia'),

    )

apps/municipios/models.py
from django.db import models


class Municipios(models.Model):
	cod_municipio = models.CharField(max_length=20)
	nombre = models.CharField(max_length=200)

	def __unicode__(self):
		return self.nombre


class Provincia(models.Model):
	cod_provincia = models.CharField(max_length=20)
	nombre = models.CharField(max_length=200)
	municipio = models.ForeignKey(Municipios, null=True, blank=True)

	def __unicode__(self):
		return self.nombre

apps/juridica/forms.py
from django import forms 


class ConveniosForm(forms.Form):
	fecha = forms.DateField(label='fecha')
	entidad = forms.CharField(max_length=100)
	objetivo = forms.CharField(max_length=100)
	contra_financiera = forms.CharField(label='contraparte financiera', max_length=100)
	vig_avance = forms.CharField(label='vigencia/avance', max_length=100)

apps/municipios/forms.py
from django import forms 


class municipiosForm(forms.Form):
    cod_municipio = forms.CharField(label='cod_municipio')
    nombre = forms.CharField(max_length=100)


class provinciasForm(forms.Form):
    cod_provincia = forms.CharField(label='cod_provincia')
    nombre = forms.CharField(max_length=100)

apps/municipios/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, FormView, ListView
from .forms import municipiosForm, provinciasForm
from django.core.urlresolvers import reverse_lazy
from .models import Municipios, Provincia

# Create your views here.
class municipios(ListView):
    model = Municipios
    template_name = 'municipios/lista.html'

class provincias(ListView):
    model = Provincia
    template_name = 'municipios/lista_provincias.html'

class Crearmunicipios(FormView):
    template_name = 'municipios/registro.html'
    form_class = municipiosForm
    success_url = reverse_lazy('municipios')

    def form_valid(self, form):
        municipio = Municipios()
        municipio.cod_municipio = form.cleaned_data['cod_municipio']
        municipio.nombre = form.cleaned_data['nombre']
        municipio.save()
        return super(Crearmunicipios, self).form_valid(form)

class Crearprovincias(FormView):
    template_name = 'municipios/registro_provincia.html'
    form_class = provinciasForm
    success_url = reverse_lazy('provincia')

    def form_valid(self, form):
        provincias = Provincia()
        provincias.cod_provincia = form.cleaned_data['cod_provincia']
        provincias.nombre = form.cleaned_data['nombre']
        provincias.save()
        return super(Crearprovincias, self).form_valid(form)

templates/municipios/lista.html
{% extends "base.html" %}
{% block contenido %}
  <!-- page content -->
        <div class="right_col" role="main">
          <div class="">
            <div class="page-title">
              

              <div class="title_right">
                <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                  <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search for...">
                    <span class="input-group-btn">
                      <button class="btn btn-default" type="button">Go!</button>
                    </span>
                  </div>
                </div>
              </div>
            </div>

            <div class="clearfix"></div>

            <div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    
                  <div class="x_content">
                    
                    <table id="datatable" class="table table-striped table-bordered">
                      <thead>
                        <tr>
                          <th>COD_MUNICIPIO</th>
                          <th>NOM_MUNICIPIO</th>
                        </tr>
                      </thead>


                      <tbody>
                        
                        {% for municipios in object_list %}
                            <tr>
                              
                              <td>{{ municipios.cod_municipio}}</td>
                              <td>{{ municipios.nombre}}</td>
          
                              
                            </tr>

                        {% endfor %}
                        
                   
                        
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>

            </div>
          </div>
        </div>
        <!-- /page content -->
{% endblock %}

templates/municipios/lista_provincias.html
{% extends "base.html" %}
{% block contenido %}
  <!-- page content -->
        <div class="right_col" role="main">
          <div class="">
            <div class="page-title">
              

              <div class="title_right">
                <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                  <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search for...">
                    <span class="input-group-btn">
                      <button class="btn btn-default" type="button">Go!</button>
                    </span>
                  </div>
                </div>
              </div>
            </div>

            <div class="clearfix"></div>

            <div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    
                  <div class="x_content">
                    
                    <table id="datatable" class="table table-striped table-bordered">
                      <thead>
                        <tr>
                          <th>COD_PROVINCIA</th>
                          <th>NOM_PROVINCIA</th>
                        </tr>
                      </thead>


                      <tbody>
                        
                        {% for provincias in object_list %}
                            <tr>
                              
                              <td>{{ provincias.cod_provincia}}</td>
                              <td>{{ provincias.nombre}}</td>
          
                              
                            </tr>

                        {% endfor %}
                        
                   
                        
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>

            </div>|
          </div>
        </div>
        <!-- /page content -->
{% endblock %}

templates/municipios/registro.html
{% extends "base.html" %}
{% block contenido %}
{% load widget_tweaks %}


<div class="right_col" role="main">
          <div class="">
            <div class="page-title">
              <div class="title_left">
                <h3>Registro Municipios</h3>
              </div>         
            </div>
            <div class="clearfix"></div>
            <div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                
                  <div class="x_content">
                    <br />
                    <form id="demo-form2" data-parsley-validate class="form-horizontal form-label-left" method="post">
						{% csrf_token %}
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Cod_Municipio<span class="required"></span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          
                          {{form.cod_municipio|add_class:"date-picker form-control col-md-7 col-xs-12"|add_error_class:"parsley-error"}}
                          {% if form.errors.cod_municipio %}
	                          <ul id="parsley-id-5" class="parsley-errors-list filled">
	                          	<li class="parsley-required">{{form.errors.cod_municipio|removetags:'ul li'}}</li>
	                          </ul>
	                       {% endif %}

                        </div>
                      </div>

                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Nom_Municipio<span class="required"></span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          {{form.nombre|add_class:"form-control col-md-7 col-xs-12"|add_error_class:"parsley-error"}}
                          {% if form.errors.entidad %}
	                          <ul id="parsley-id-5" class="parsley-errors-list filled">
	                          	<li class="parsley-required">{{form.errors.nombre|removetags:'ul li'}}</li>
	                          </ul>
	                       {% endif %}

                        </div>
                      </div>

                      <div class="ln_solid"></div>
                      <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                          <button type="submit" class="btn btn-primary">Cancelar</button>
                          <button type="submit" class="btn btn-success">Guardar</button>
                        </div>
                      </div>

                    </form>
                  </div>
                </div>
              </div>
            </div>

           

         



           
          </div>
        </div>


{% endblock %}
{% block js %}
	<script>
      
        $('#id_fecha').daterangepicker({
          singleDatePicker: true,
          calender_style: "picker_4",
          locale: {
            format: 'DD/MM/YYYY'
          }
        }, function(start, end, label) {
          console.log(start.toISOString(), end.toISOString(), label);
        });

    </script>
{% endblock js %}

templates/municipios/registro_provincia.html
{% extends "base.html" %}
{% block contenido %}
{% load widget_tweaks %}


<div class="right_col" role="main">
          <div class="">
            <div class="page-title">
              <div class="title_left">
                <h3>Registro Provincias</h3>
              </div>         
            </div>
            <div class="clearfix"></div>
            <div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                
                  <div class="x_content">
                    <br />
                    <form id="demo-form2" data-parsley-validate class="form-horizontal form-label-left" method="post">
						{% csrf_token %}
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Cod_Provincia<span class="required"></span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          
                          {{form.cod_provincia|add_class:"date-picker form-control col-md-7 col-xs-12"|add_error_class:"parsley-error"}}
                          {% if form.errors.cod_provincia %}
	                          <ul id="parsley-id-5" class="parsley-errors-list filled">
	                          	<li class="parsley-required">{{form.errors.cod_provincia|removetags:'ul li'}}</li>
	                          </ul>
	                       {% endif %}

                        </div>
                      </div>

                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Nom_provincia<span class="required"></span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          {{form.nombre|add_class:"form-control col-md-7 col-xs-12"|add_error_class:"parsley-error"}}
                          {% if form.errors.entidad %}
	                          <ul id="parsley-id-5" class="parsley-errors-list filled">
	                          	<li class="parsley-required">{{form.errors.nombre|removetags:'ul li'}}</li>
	                          </ul>
	                       {% endif %}

                        </div>
                      </div>

                      <div class="ln_solid"></div>
                      <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                          <button type="submit" class="btn btn-primary">Cancelar</button>
                          <button type="submit" class="btn btn-success">Guardar</button>
                        </div>
                      </div>

                    </form>
                  </div>
                </div>
              </div>
            </div>

           

         



           
          </div>
        </div>


{% endblock %}
{% block js %}
	<script>
      
        $('#id_fecha').daterangepicker({
          singleDatePicker: true,
          calender_style: "picker_4",
          locale: {
            format: 'DD/MM/YYYY'
          }
        }, function(start, end, label) {
          console.log(start.toISOString(), end.toISOString(), label);
        });

    </script>
{% endblock js %}