andeco/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('apps.inicio.urls')),
    url(r'^', include('apps.finanzas.urls')),
    url(r'^', include('apps.juridica.urls')),
    url(r'^', include('apps.municipios.urls')),
    url(r'^', include('apps.Planificacion.urls')),

]

apps/finanzas/urls.py
from django.conf.urls import patterns, url
from .views import Finanzas, EditTrabajo, EditAsistencia, EditCurso

urlpatterns = patterns('',
	url(r'^finansas/$', Finanzas.as_view(), name='finansas'),
	url(r'^proyectoFinanzas/$', 'apps.finanzas.views.createProyecto', name='proyectoFinanzas'),
    url(r'^lista_finanzas/$', 'apps.finanzas.views.listadoFinanzas', name='lista_finanzas'),
    url(r'^delete_trabajo/(?P<id>\d+)$', 'apps.finanzas.views.eliminarTrabajo', name='delete_trabajo'),
    url(r'^editar_trabajo/(?P<pk>\d+)$', EditTrabajo.as_view(), name='editar_trabajo'),
    url(r'^lista_asistencia/$', 'apps.finanzas.views.listadoAsistencia', name='lista_asistencia'),
	url(r'^crear_asistencia/$', 'apps.finanzas.views.createAsistencia', name='crear_asistencia'),
    url(r'^delete_asistencia/(?P<id>\d+)$', 'apps.finanzas.views.eliminarAsistencia', name='delete_asistencia'),
    url(r'^editar_asistencia/(?P<pk>\d+)$', EditAsistencia.as_view(), name='editar_asistencia'),
    url(r'^lista_cursos/$', 'apps.finanzas.views.listadoCursos', name='lista_cursos'),
	url(r'^crear_curso/$', 'apps.finanzas.views.createCurso', name='crear_curso'),
    url(r'^delete_curso/(?P<id>\d+)$', 'apps.finanzas.views.eliminarCurso', name='delete_curso'),
    url(r'^editar_curso/(?P<pk>\d+)$', EditCurso.as_view(), name='editar_curso'),

)

apps/finanzas/models.py
from django.db import models
from taggit.managers import TaggableManager


class proyectoFinanzas(models.Model):
	codigo = models.CharField(max_length=200)
	nombre_proyecto = models.CharField(max_length=200)
	region = models.CharField(max_length=200)
	municipio = models.CharField(max_length=200)
	responsable_proyecto = models.CharField(max_length=200)
	fecha_inicio = models.DateField(null=True, blank=True)
	fecha_conclucion = models.DateField(null=True, blank=True)
	objetivo = models.CharField(max_length=200)
	avance = models.IntegerField(null=True, blank=True)

	def __unicode__(self):
		return self.nombre_proyecto


class Asistencia(models.Model):
	nombre = models.CharField(max_length=200)
	region = models.CharField(max_length=200)
	municipio = models.CharField(max_length=200)
	responsable = models.CharField(max_length=200)
	fecha_inicio = models.DateField(null=True, blank=True)
	fecha_conclucion = models.DateField(null=True, blank=True)
	objetivo = models.CharField(max_length=200)
	estado = models.CharField(max_length=200, null=True, blank=True)

	def __unicode__(self):
		return self.nombre


class Cursos(models.Model):
	titulo = models.CharField(max_length=200)
	area = models.CharField(max_length=200)
	costo = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
	material = models.CharField(max_length=200)
	region = models.CharField(max_length=200)
	municipios = TaggableManager()
	responsable = models.CharField(max_length=200)
	fecha_inicio = models.DateField(null=True, blank=True)
	fecha_conclucion = models.DateField(null=True, blank=True)
	objetivo = models.CharField(max_length=200)
	# choice_field = models.CharField(choices=list_of_choices, max_length=50, null=True, blank=True)

	def __unicode__(self):
		return self.titulo

apps/finanzas/forms.py
# -*- coding: utf-8 -*-
from django import forms
from .models import Cursos


lista_region = (
    ('', '--- seleccionar---'),
    (1, 'Metropolitana'),
    (2, 'Vallez'),
    (3, 'Tropico'),
    (4, 'Cono sur'),
    (5, 'Andina'),
)

lista_estado = (
	('No iniciado', 'No iniciado'),
    ('En proceso', 'En proceso'),
    ('Finalizado', 'Finalizado'),
)


class createProyectForm(forms.Form):
    codigo = forms.CharField(max_length=100)
    nombre_proyecto = forms.CharField(max_length=100)
    region = forms.ChoiceField(choices=lista_region)
    municipio = forms.CharField(max_length=100)
    responsable_proyecto = forms.CharField()
    fecha_inicio = forms.CharField()
    fecha_conclucion = forms.CharField()
    objetivo = forms.CharField(max_length=100)
    avance = forms.CharField(max_length=100)


class AsistenciaForm(forms.Form):
    nombre = forms.CharField(max_length=100)
    region = forms.ChoiceField(choices=lista_region)
    municipio = forms.CharField(max_length=100)
    responsable = forms.CharField()
    fecha_inicio = forms.CharField()
    fecha_conclucion = forms.CharField()
    objetivo = forms.CharField(max_length=100, widget=forms.Textarea(attrs={'rows':3}))
    estado = forms.ChoiceField(choices=lista_estado)


list_of_choices = (
    ("cochabamba", "cochabamba"),
    ("Colcapirhua", "Colcapirhua"),
    ("Quillacollo", "Quillacollo"),
    ("Sacaba", "Sacaba"),
    ("Sipe Sipe", "Sipe Sipe"),
    ("Vinto", "Vinto"),
    ("Punata", "Punata"),
    ("Capinota", "Capinota"),
    ("Santivañes", "Santivañes"),
    ("Arani", "Arani"),
    ("Villa Rivero", "Villa Rivero"),
    ("Cliza", "Cliza"),
    ("Toco", "Toco"),
    ("Tolata", "Tolata"),
    ("Tarata", "Tarata"),
    ("Anzaldo", "Anzaldo"),
    ("Sacabamba", "Sacabamba"),
    ("Arbieto", "Arbieto"),
    ("Tacahi", "Tacahi"),
    ("Villa Gualberto Villarroel", "Villa Gualberto Villarroel"),
    ("San Benito", "San Benito"),
    ("Entre Rios", "Entre Rios"),
    ("Shinahota", "Shinahota"),
    ("Colomi", "Colomi"),
    ("Puerto Villarroel", "Puerto Villarroel"),
    ("Villa Tunari", "Villa Tunari"),
    ("Chimore", "Chimore"),
    ("Vacas", "Vacas"),
    ("Tiraque", "Tiraque"),
    ("Alalay", "Alalay"),
    ("Mizque", "Mizque"),
    ("Aiquile", "Aiquile"),
    ("Vila Vila", "Vila Vila"),
    ("Pojo", "Pojo"),
    ("Omereque", "Omereque"),
    ("Totora", "Totora"),
    ("Pocona", "Pocona"),
    ("Pasorapa", "Pasorapa"),
    ("Bolivar", "Bolivar"),
    ("Cocapata", "Cocapata"),
    ("independencia", "independencia"),
    ("Morochata", "Morochata"),
    ("Tapacari", "Tapacari"),
    ("Tacopaya", "Tacopaya"),
    ("Sicaya", "Sicaya"),
    ("Arque", "Arque"),
)


class CursoForm(forms.Form):
    titulo = forms.CharField(max_length=100)
    area = forms.CharField()
    costo = forms.DecimalField()
    material = forms.CharField(max_length=100)
    region = forms.ChoiceField(choices=lista_region)
    # choice_field = forms.MultipleChoiceField(choices=list_of_choices)
    municipios = forms.MultipleChoiceField(choices=list_of_choices)
    responsable = forms.CharField()
    fecha_inicio = forms.CharField()
    fecha_conclucion = forms.CharField()
    objetivo = forms.CharField(max_length=100, widget=forms.Textarea(attrs={'rows':3}))


class CursoEditForm(forms.ModelForm):
    titulo = forms.CharField(max_length=100)
    area = forms.CharField()
    costo = forms.DecimalField()
    material = forms.CharField(max_length=100)
    region = forms.ChoiceField(choices=lista_region)
    # choice_field = forms.MultipleChoiceField(choices=list_of_choices)
    municipios = forms.MultipleChoiceField(choices=list_of_choices)
    responsable = forms.CharField()
    fecha_inicio = forms.CharField()
    fecha_conclucion = forms.CharField()
    objetivo = forms.CharField(max_length=100, widget=forms.Textarea(attrs={'rows':3}))

    class Meta:
        model = Cursos
        fields = ('titulo', 'area', 'costo', 'material', 'region', 'municipios', 'responsable', 'fecha_inicio', 'fecha_conclucion', 'objetivo')

apps/finanzas/views.py
from django.shortcuts import render_to_response, render
from django.views.generic import TemplateView, UpdateView
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse_lazy
from .models import proyectoFinanzas, Asistencia, Cursos
from .forms import createProyectForm, AsistenciaForm, CursoForm, CursoEditForm
from django.template import RequestContext
from django import forms


# Create your views here.
class Finanzas(TemplateView):
    template_name = 'finanzas/lista.html'


def createProyecto(request):
    if request.method == 'POST':
        form = createProyectForm(request.POST)
        if form.is_valid():
            print 'sdfdsfdsfdsfds'
            proyectos = proyectoFinanzas(
                codigo=form.cleaned_data['codigo'],
                nombre_proyecto=form.cleaned_data['nombre_proyecto'],
                region=form.cleaned_data['region'],
                municipio=form.cleaned_data['municipio'],
                responsable_proyecto=form.cleaned_data['responsable_proyecto'],
                fecha_inicio=form.cleaned_data['fecha_inicio'],
                fecha_conclucion=form.cleaned_data['fecha_conclucion'],
                objetivo=form.cleaned_data['objetivo'],
                avance=form.cleaned_data['avance'])
            proyectos.save()

            return HttpResponseRedirect(reverse_lazy('lista_finanzas'))
    else:
        form = createProyectForm()
    variables = RequestContext(request, {'form': form})
    return render_to_response('finanzas/crear_proyectos.html', variables)


def listadoFinanzas(request):
    print request.user.pk
    proyectos = proyectoFinanzas.objects.all()
    variables = RequestContext(request, {'proyectos': proyectos})

    return render_to_response('finanzas/listado_finanzas.html', variables)


def eliminarTrabajo(request, id):
    p = proyectoFinanzas.objects.get(id=id)
    p.delete()
    return HttpResponseRedirect(reverse_lazy('lista_finanzas'))


class EditTrabajo(UpdateView):
    template_name = "finanzas/edit_trabajo.html"
    model = proyectoFinanzas
    fields = ['codigo', 'nombre_proyecto', 'region', 'municipio', 'responsable_proyecto', 'fecha_inicio', 'fecha_conclucion', 'objetivo', 'avance']
    success_url = reverse_lazy('lista_finanzas')

    def get_form(self, form_class):
        form = super(EditTrabajo, self).get_form(form_class)
        form.fields['fecha_inicio'].widget = forms.DateInput(format='%Y-%m-%d')
        form.fields['fecha_conclucion'].widget = forms.DateInput(format='%Y-%m-%d')
        return form


def listadoAsistencia(request):
    print request.user.pk
    asistencia = Asistencia.objects.all()
    variables = RequestContext(request, {'asistencia': asistencia})

    return render_to_response('finanzas/listado_asistencia.html', variables)


def createAsistencia(request):
    if request.method == 'POST':
        form = AsistenciaForm(request.POST)
        if form.is_valid():
            print 'sdfdsfdsfdsfds'
            asistencia = Asistencia(
                nombre=form.cleaned_data['nombre'],
                region=form.cleaned_data['region'],
                municipio=form.cleaned_data['municipio'],
                responsable=form.cleaned_data['responsable'],
                fecha_inicio=form.cleaned_data['fecha_inicio'],
                fecha_conclucion=form.cleaned_data['fecha_conclucion'],
                objetivo=form.cleaned_data['objetivo'],
                estado=form.cleaned_data['estado'])
            asistencia.save()

            return HttpResponseRedirect(reverse_lazy('lista_asistencia'))
    else:
        form = AsistenciaForm()
    variables = RequestContext(request, {'form': form})
    return render_to_response('finanzas/crear_asistencia.html', variables)


def eliminarAsistencia(request, id):
    p = Asistencia.objects.get(id=id)
    p.delete()
    return HttpResponseRedirect(reverse_lazy('lista_asistencia'))


class EditAsistencia(UpdateView):
    template_name = "finanzas/edit_asistencia.html"
    model = Asistencia
    fields = ['nombre', 'region', 'municipio', 'responsable', 'fecha_inicio', 'fecha_conclucion', 'objetivo', 'estado']
    success_url = reverse_lazy('lista_asistencia')

    def get_form(self, form_class):
        form = super(EditAsistencia, self).get_form(form_class)
        form.fields['fecha_inicio'].widget = forms.DateInput(format='%Y-%m-%d')
        form.fields['fecha_conclucion'].widget = forms.DateInput(format='%Y-%m-%d')
        form.fields['objetivo'].widget = forms.Textarea(attrs={'rows':3})
        return form

def listadoCursos(request):
    print request.user.pk
    cursos = Cursos.objects.all()
    variables = RequestContext(request, {'cursos': cursos})

    return render_to_response('finanzas/listado_cursos.html', variables)


def createCurso(request):
    if request.method == 'POST':
        form = CursoForm(request.POST)
        if form.is_valid():
            print 'sdfdsfdsfdsfds'
            curso = Cursos(
                titulo=form.cleaned_data['titulo'],
                area=form.cleaned_data['area'],
                costo=form.cleaned_data['costo'],
                material=form.cleaned_data['material'],
                region=form.cleaned_data['region'],
                responsable=form.cleaned_data['responsable'],
                fecha_inicio=form.cleaned_data['fecha_inicio'],
                fecha_conclucion=form.cleaned_data['fecha_conclucion'],
                objetivo=form.cleaned_data['objetivo'])

            municipios = form.cleaned_data.pop('municipios')
            curso.save()
            print 'los muinsssssss'
            print municipios
            # print ', '.join([str(x) for x in municipios])
            # print str(municipios).strip('[]')
            # curso.municipios.add(str(municipios).strip('[]'))

            for m in municipios:
                curso.municipios.add(m)
            # for c in choice_fields:
            #     Subjects.objects.create(subject=c)

            return HttpResponseRedirect(reverse_lazy('lista_cursos'))
    else:
        form = CursoForm()
    variables = RequestContext(request, {'form': form})
    return render_to_response('finanzas/crear_curso.html', variables)


def eliminarCurso(request, id):
    p = Cursos.objects.get(id=id)
    p.delete()
    return HttpResponseRedirect(reverse_lazy('lista_cursos'))


# class EditCurso(UpdateView):
#     template_name = "finanzas/edit_curso.html"
#     model = Cursos
#     # form_class = CursoForm
#     fields = ['fecha', 'titulo', 'area', 'costo', 'duracion', 'material', 'region', 'municipios']
#     success_url = reverse_lazy('lista_cursos')

#     def get_form(self, form_class):
#         form = super(EditCurso, self).get_form(form_class)
#         form.fields['fecha'].widget = forms.DateInput(format='%Y-%m-%d')
#         form.fields['municipios'].widget = forms.MultipleChoiceField(choices=list_of_choices)
#         return form

class EditCurso(UpdateView):
    template_name = "finanzas/edit_curso.html"
    model = Cursos
    form_class = CursoEditForm
    success_url = reverse_lazy('lista_cursos')

templates/finanzas/crear_asistencia.html
{% extends "base.html" %}
{% block contenido %}
{% load widget_tweaks %}


<div class="right_col" role="main">
          <div class="">
            <div class="page-title">
              <div class="title_left">
                <h3>Registro Asistencia</h3>
              </div>         
            </div>
            <div class="clearfix"></div>
            <div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                
                  <div class="x_content">
                    <br />
                    <form id="demo-form2" data-parsley-validate class="form-horizontal form-label-left" method="post">
                    {% csrf_token %}
               
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Nombre <span class="required"></span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          
                          {{form.nombre|add_class:" form-control col-md-7 col-xs-12"|add_error_class:"parsley-error"}}
                          {% if form.errors.nombre %}
                            <ul id="parsley-id-5" class="parsley-errors-list filled">
                              <li class="parsley-required">{{form.errors.nombre|removetags:'ul li'}}</li>
                            </ul>
                         {% endif %}

                        </div>
                      </div>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Region<span class="required"></span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          
                          {{form.region|add_class:" form-control col-md-7 col-xs-12"|add_error_class:"parsley-error"}}
                          {% if form.errors.region %}
                            <ul id="parsley-id-5" class="parsley-errors-list filled">
                              <li class="parsley-required">{{form.errors.region|removetags:'ul li'}}</li>
                            </ul>
                         {% endif %}

                        </div>
                      </div>

                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Municipio<span class="required"></span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          
                          <select class="form-control col-md-7 col-xs-12 {% if form.errors.municipio %}parsley-error{% endif %}" id="id_municipio" name="municipio">
                            <option value="">Seleccione el municipio</option>
                          </select>
                          {% if form.errors.municipio %}
                            <ul id="parsley-id-5" class="parsley-errors-list filled">
                              <li class="parsley-required">{{form.errors.municipio|removetags:'ul li'}}</li>
                            </ul>
                         {% endif %}

                        </div>
                      </div>

                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Responsable<span class="required"></span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          {{form.responsable|add_class:"form-control col-md-7 col-xs-12"|add_error_class:"parsley-error"}}
                          {% if form.errors.responsable %}
                            <ul id="parsley-id-5" class="parsley-errors-list filled">
                              <li class="parsley-required">{{form.errors.responsable|removetags:'ul li'}}</li>
                            </ul>
                         {% endif %}

                        </div>
                      </div>


                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Fecha de Inicio<span class="required"></span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          
                          {{form.fecha_inicio|add_class:"date-picker form-control col-md-7 col-xs-12"|add_error_class:"parsley-error"}}
                          {% if form.errors.fecha_inicio %}
                            <ul id="parsley-id-5" class="parsley-errors-list filled">
                              <li class="parsley-required">{{form.errors.fecha_inicio|removetags:'ul li'}}</li>
                            </ul>
                         {% endif %}

                        </div>
                      </div>

                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Fecha de Conclucion<span class="required"></span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          
                          {{form.fecha_conclucion|add_class:"date-picker form-control col-md-7 col-xs-12"|add_error_class:"parsley-error"}}
                          {% if form.errors.fecha_conclucion %}
                            <ul id="parsley-id-5" class="parsley-errors-list filled">
                              <li class="parsley-required">{{form.errors.fecha_conclucion|removetags:'ul li'}}</li>
                            </ul>
                         {% endif %}

                        </div>
                      </div>

                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Objetivo<span class="required"></span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          
                          {{form.objetivo|add_class:" form-control col-md-7 col-xs-12"|add_error_class:"parsley-error"}}
                          {% if form.errors.objetivo %}
                            <ul id="parsley-id-5" class="parsley-errors-list filled">
                              <li class="parsley-required">{{form.errors.objetivo|removetags:'ul li'}}</li>
                            </ul>
                         {% endif %}

                        </div>
                      </div>

                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Estado<span class="required"></span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          
                          {{form.estado|add_class:" form-control col-md-7 col-xs-12"|add_error_class:"parsley-error"}}
                          {% if form.errors.estado %}
                            <ul id="parsley-id-5" class="parsley-errors-list filled">
                              <li class="parsley-required">{{form.errors.estado|removetags:'ul li'}}</li>
                            </ul>
                         {% endif %}

                         

                        </div>
                      </div>
                      <div class="ln_solid"></div>
                      <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                          <button type="submit" class="btn btn-primary">Cancelar</button>
                          <button type="submit" class="btn btn-success">Guardar</button>
                        </div>
                      </div>

                    </form>
                  </div>
                </div>
              </div>
            </div>

           

         



           
          </div>
        </div>


{% endblock %}
{% block js %}
  {% load staticfiles %}
  <script src="{% static "js/ion.rangeSlider.js"%}"></script>
  <script>
      
        


         $('#id_fecha_inicio').daterangepicker({
          singleDatePicker: true,
          calender_style: "picker_4",
          locale: {
            format: 'YYYY-MM-DD'
          }
        }, function(start, end, label) {
          console.log(start.toISOString(), end.toISOString(), label);
        });

        $('#id_fecha_conclucion').daterangepicker({
          singleDatePicker: true,
          calender_style: "picker_4",
          locale: {
            format: 'YYYY-MM-DD'
          }
        }, function(start, end, label) {
          console.log(start.toISOString(), end.toISOString(), label);
        });

        


        var Metropolitana = [
          {display: "Cochabamba", value: "cochabamba"},
          {display: "Colcapirhua", value: "Colcapirhua"},
          {display: "Quillacollo", value: "Quillacollo"},
          {display: "Sacaba", value: "Sacaba"},
          {display: "Sipe Sipe", value: "Sipe Sipe"},
          {display: "Vinto", value: "Vinto"}];

        var Vallez = [
          {display:"Punata", value:"Punata"},
          {display:"Capinota", value:"Capinota"},
          {display:"Santivañes", value:"Santivañes"},
          {display:"Arani", value:"Arani"},
          {display:"Villa Rivero", value:"Villa Rivero"},
          {display:"Cliza", value:"Cliza"},
          {display:"Toco", value:"Toco"},
          {display:"Tolata", value:"Tolata"},
          {display:"Tarata", value:"Tarata"},
          {display:"Anzaldo", value:"Anzaldo"},
          {display:"Sacabamba", value:"Sacabamba"},
          {display:"Arbieto", value:"Arbieto"},
          {display:"Tacahi", value:"Tacahi"},
          {display:"Villa Gualberto Villarroel", value:"Villa Gualberto Villarroel"},
          {display:"San Benito", value:"San Benito"}];

          var Tropico = [
          {display:"Entre Rios", value:"Entre Rios"},
          {display:"Shinahota", value:"Shinahota"},
          {display:"Colomi", value:"Colomi"},
          {display:"Puerto Villarroel", value:"Puerto Villarroel"},
          {display:"Villa Tunari", value:"Villa Tunari"},
          {display:"Chimore", value:"Chimore"}];

          var Conosur = [
          {display:"Vacas", value:"Vacas"},
          {display:"Tiraque", value:"Tiraque"},
          {display:"Alalay", value:"Alalay"},
          {display:"Mizque", value:"Mizque"},
          {display:"Aiquile", value:"Aiquile"},
          {display:"Vila Vila", value:"Vila Vila"},
          {display:"Pojo", value:"Pojo"},
          {display:"Omereque", value:"Omereque"},
          {display:"Totora", value:"Totora"},
          {display:"Pocona", value:"Pocona"},
          {display:"Pasorapa", value:"Pasorapa"}];

           var Andina = [
          {display:"Bolivar", value:"Bolivar"},
          {display:"Cocapata", value:"Cocapata"},
          {display:"independencia", value:"independencia"},
          {display:"Morochata", value:"Morochata"},
          {display:"Tapacari", value:"Tapacari"},
          {display:"Tacopaya", value:"Tacopaya"},
          {display:"Sicaya", value:"Sicaya"},
          {display:"Arque", value:"Arque"}];
         
        
            //If parent option is changed
        $("#id_region").change(function() {
                var parent = $(this).val(); //get option value from parent 

                switch(parent){ //using switch compare selected option and populate child
                        case '1':
                        list(Metropolitana);
                        break;  
                        case '2':
                        list(Vallez);
                        break;
                        case '3':
                        list(Tropico);
                        break;
                        case '4':
                        list(Conosur);
                        break;
                        case '5':
                        list(Andina);
                        break;
                    default: //default child option is blank
                        $("#id_municipio").html('');  
                        break;
                }
          });
          //function to populate child select box
          function list(array_list){
               //reset child options
               $("#id_municipio").html(""); 
              $(array_list).each(function (i) { //populate child options 
                  console.log(i);
         

              $("#id_municipio").append("<option value=\""+array_list[i].value+"\">"+array_list[i].display+"</option>");
             

              });
          }
        



    </script>
{% endblock js %}

templates/finanzas/lista.html
{% extends "base.html" %}
{% block contenido %}
  <!-- page content -->
        <div class="right_col" role="main">
          <div class="">
            <div class="page-title">
              

              <div class="title_right">
                <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                  <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search for...">
                    <span class="input-group-btn">
                      <button class="btn btn-default" type="button">Go!</button>
                    </span>
                  </div>
                </div>
              </div>
            </div>

            <div class="clearfix"></div>

            <div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    
                  <div class="x_content">
                    
                    <table id="datatable" class="table table-striped table-bordered">
                      <thead>
                        <tr>
                          <th>CODIGO</th>
                          <th>NOMBRE</th>
                          <th>REGION</th>
                          <th>MUNICIPIO</th>
                          <th>RESPONSABLE</th>
                          <th>FECHA_INICIO</th>
                          <th>FECHA_FINAL</th>
                          <th>OBJETIVO</th>
                          <th>AVANCE</th>
                        </tr>
                      </thead>


                      <tbody>
                        
                        {% for finazas in object_list %}
                            <tr>
                              <td>{{forloop.counter}}</td>
                              <td>{{ finazas.codigo}}</td>
                              <td>{{ finazas.nombre}}</td>
                              <td>{{ finazas.region}}</td>
                              <td>{{ finazas.municipio}}</td>
                              <td>{{ finazas.responsable}}</td>
                              <td>{{ finazas.fecha_inicio}}</td>
                              <td>{{ finazas.fecha_final}}</td>
                              <td>{{ finazas.objetivo}}</td>
                              <td>{{ finazas.avance}}</td>

                              
                            </tr>

                        {% endfor %}
                        
                   
                        
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>

            </div>
          </div>
        </div>
        <!-- /page content -->
{% endblock %}