andeco/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('apps.inicio.urls')),
    url(r'^', include('apps.finanzas.urls')),
    url(r'^', include('apps.juridica.urls')),
    url(r'^', include('apps.municipios.urls')),
    url(r'^', include('apps.Planificacion.urls')),

]

apps/Planificacion/urls.py
from django.conf.urls import patterns, url
#from .views import CrearResponsables
from .views import ListadoResponsables, EditProyecto, EditInspecion

urlpatterns = patterns('',
    # url(r'^responsables/$', Juridica.as_view(), name='responsables'),
    url(r'^crear_responsables/$', 'apps.Planificacion.views.CrearResponsables', name='crear_responsables'),
    url(r'^listado_responsables/$', ListadoResponsables.as_view(), name='listado_responsables'),

    url(r'^crear_planificacion/$', 'apps.Planificacion.views.CrearPlanificacion', name='crear_planificacion'),
    url(r'^crear_etapa/(?P<pk>\d+)$', 'apps.Planificacion.views.CrearEtapa', name='crear_etapa'),
    url(r'^lista_etapas/(?P<pk>\d+)$', 'apps.Planificacion.views.listaEtapas', name='lista_etapas'),
    url(r'^lista_proyectos/$', 'apps.Planificacion.views.listadoProyectos', name='lista_proyectos'),
    url(r'^reporte_gantt/(?P<pk>\d+)$', 'apps.Planificacion.views.ReporteGantt', name='reporte_gantt'),
    url(r'^gantt_ajax/(?P<pk>\d+)$', 'apps.Planificacion.views.GanttAjax', name='gantt_ajax'),
    url(r'^delete_proyect/(?P<id>\d+)$', 'apps.Planificacion.views.eliminarProyecto', name='delete_proyect'),
    url(r'^editar_proyecto/(?P<pk>\d+)$', EditProyecto.as_view(), name='editar_proyecto'),
    url(r'^lista_inspeccion/(?P<pk>\d+)$', 'apps.Planificacion.views.listaInspeccion', name='lista_inspeccion'),
    url(r'^ajax_inspeccion/(?P<pk>\d+)$', 'apps.Planificacion.views.listaInspeccionAjax', name='ajax_inspeccion'),
    url(r'^crear_inspeccion/(?P<pk>\d+)$', 'apps.Planificacion.views.CrearInspeccion', name='crear_inspeccion'),
    url(r'^delete_inspeccion/(?P<id>\d+)$', 'apps.Planificacion.views.eliminarInspeccion', name='delete_inspeccion'),
    url(r'^editar_inspeccion/(?P<pk>\d+)$', EditInspecion.as_view(), name='editar_inspeccion'),



    )

apps/Planificacion/models.py
from django.db import models
from django.conf import settings
from apps.users.models import User


class Proyectos(models.Model):
	region = models.CharField(max_length=200)
	municipio = models.CharField(max_length=200)
	nombre_proyecto = models.CharField(max_length=200)
	# responsable_proyecto = models.CharField(max_length=200)
	responsable_proyecto = models.ForeignKey(User, null=True, blank=True)
	responsable_seguimiento = models.CharField(max_length=200)
	porcentage_global = models.IntegerField(null=True, blank=True)
	fecha_inicio = models.DateField(null=True, blank=True)
	fecha_conclucion = models.DateField(null=True, blank=True)

	def __unicode__(self):
		return self.nombre_proyecto


class Etapas(models.Model):
	fecha_inicio = models.DateField()
	fecha_conclucion = models.DateField()
	nombre_etapa = models.CharField(max_length=200)
	avance = models.CharField(max_length=200)
	dias = models.IntegerField()
	observaciones = models.CharField(max_length=200)
	informe = models.CharField(max_length=200)
	proyecto = models.ForeignKey(Proyectos, null=True, blank=True)
	
	def __unicode__(self):
		return self.nombre_etapa


class Inspeccion(models.Model):
	fecha = models.DateField()
	hora = models.TimeField()
	objectivo = models.CharField(max_length=200)
	avance = models.CharField(max_length=200)
	etapa = models.ForeignKey(Etapas, null=True, blank=True)
	
	def __unicode__(self):
		return self.objectivo


class Responsables(models.Model):
	nombre = models.CharField(max_length=200)
	codigo = models.CharField(max_length=200)
	ci = models.CharField(max_length=200)
	telefono = models.CharField(max_length=200)
	direccion = models.CharField(max_length=200)
	proyecto = models.ForeignKey(Proyectos, null=True, blank=True)

	def __unicode__(self):
		return self.nombre

apps/Planificacion/forms.py
from django import forms 
from apps.users.models import User


class responsablesForm(forms.Form):
	nombre = forms.CharField(label='nombre')
	codigo = forms.CharField(max_length=100)
	ci = forms.CharField(max_length=100)
	telefono = forms.CharField(label='telefono', max_length=100)
	direccion = forms.CharField(label='direccion', max_length=100)


# class proyectosForm(forms.Form):
# 	cod = forms.CharField(max_length=100)
# 	nombre = forms.CharField(label='nombre')
# 	porcentaje_global = forms.CharField(label='porcentaje_global')


lista_region = (
	('', '--- seleccionar---'),
	(1, 'Metropolitana'),
	(2, 'Vallez'),
	(3, 'Tropico'),
	(4, 'Cono sur'),
	(5, 'Andina'),
)


class proyectosForm(forms.Form):
	regiones = forms.ChoiceField(choices=lista_region)
	municipios = forms.CharField(max_length=100)
	nombre_proyecto = forms.CharField()
	# responsable_proyecto = forms.CharField()
	responsable_proyecto = forms.ModelChoiceField(queryset=User.objects.filter(is_staff=False, is_superuser=False, area='Planificacion'))
	responsable_seguimiento = forms.CharField()
	fecha_inicio = forms.CharField()
	fecha_conclucion = forms.CharField()


class inspeccionForm(forms.Form):
	objetivo = forms.CharField(max_length=100, widget=forms.Textarea(attrs={'rows':3}))
	avance = forms.CharField()
	

apps/Planificacion/views.py
from django.shortcuts import render_to_response, render
from django.views.generic import TemplateView, FormView, ListView, UpdateView
from .forms import responsablesForm, proyectosForm, inspeccionForm
from django.core.urlresolvers import reverse_lazy
from .models import Responsables, Proyectos, Etapas, Inspeccion

from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponseRedirect, HttpResponse
from django.template import RequestContext
import json
from decimal import Decimal, ROUND_HALF_UP
from django.core.serializers.json import DjangoJSONEncoder
import datetime, time
from django import forms
from apps.inicio.roles import *
from rolepermissions.verifications import has_role


# Create your views here.
def CrearResponsables(request):
    if request.method == 'POST':
        form = responsablesForm(request.POST)
        if form.is_valid():
            responsables = Responsables(
                nombre = form.cleaned_data['nombre'],
                codigo = form.cleaned_data['codigo'],
                ci = form.cleaned_data['ci'],
                telefono = form.cleaned_data['telefono'],
                direccion = form.cleaned_data['direccion'])
            responsables.save()
            return HttpResponseRedirect(reverse_lazy('listado_responsables'))
    else:
        form = responsablesForm()
    variables = RequestContext(request, {'form': form})
    return render_to_response('planificacion/registro_responsable.html', variables)


class ListadoResponsables(ListView):
    model = Responsables
    template_name = 'planificacion/listado_responsables.html'


# class listadoProyectos(ListView):
#     model = Proyectos
#     template_name = 'planificacion/listado_Proyectos.html'


def listadoProyectos(request):
    print request.user.pk
    # if request.user.is_authenticated():
    #     if has_role(request.user, [Operador, 'admin1']):
    #         proyectos = Proyectos.objects.filter(responsable_proyecto=request.user)
    #     else:
    #         proyectos = Proyectos.objects.all()
    # else:
    proyectos = Proyectos.objects.all()

    data = []
    for p in proyectos:
        etapas = Etapas.objects.filter(proyecto=p.pk)
        avance = 0
        porcentage = 0
        cant_etapa = 0
        for e in etapas:
            cant_etapa = cant_etapa + 1
            avance = avance + Decimal(e.avance)
        print '------------'
        print avance
        print cant_etapa
        if avance != 0 and cant_etapa != 0:
            porcentage = avance / cant_etapa
            proyecto = Proyectos.objects.filter(pk=p.pk)
            proyecto.update(porcentage_global=porcentage)

        if porcentage != 0:
            redondeado = Decimal(porcentage.quantize(Decimal('.01'), rounding=ROUND_HALF_UP))
        else:
            redondeado = 0

        data.append({'pk': p.pk, 'region': p.region, 'municipio': p.municipio, 'nombre_proyecto': p.nombre_proyecto, 'responsable_proyecto': p.responsable_proyecto, 'responsable_seguimiento': p.responsable_seguimiento, 'porcentage_global': redondeado })

    variables = RequestContext(request, {'object_list': data})

    return render_to_response('planificacion/listado_Proyectos.html', variables)



def Crearproyecto(request):
    if request.method == 'POST':
        form = proyectosForm(request.POST)
        if form.is_valid():
            proyectos = Proyectos(
                nombre=form.cleaned_data['nombre'],
                codigo=form.cleaned_data['codigo'],
                porcentaje_global=form.cleaned_data['porcentaje_global'])
            proyectos.save()
            return HttpResponseRedirect(reverse_lazy('listado_responsables'))
    else:
        form = proyectosForm()
    variables = RequestContext(request, {'form': form})
    return render_to_response('proyectos/proyectos.html', variables)


def CrearPlanificacion(request):
    if request.method == 'POST':
        form = proyectosForm(request.POST)
        if form.is_valid():
            proyectos = Proyectos(
                region=form.cleaned_data['regiones'],
                municipio=form.cleaned_data['municipios'],
                nombre_proyecto=form.cleaned_data['nombre_proyecto'],
                responsable_proyecto=form.cleaned_data['responsable_proyecto'],
                responsable_seguimiento=form.cleaned_data['responsable_seguimiento'],
                porcentage_global=0,
                fecha_inicio=form.cleaned_data['fecha_inicio'],
                fecha_conclucion=form.cleaned_data['fecha_conclucion'])
               
            proyectos.save()
            return HttpResponseRedirect(reverse_lazy('crear_etapa', kwargs={'pk':proyectos.pk}))
    else:
        form = proyectosForm()
    variables = RequestContext(request, {'form': form})

    return render_to_response('planificacion/crear_planificacion.html', variables)


def CrearEtapa(request, pk):
    if request.method == 'POST':
        etapa = Etapas(
          fecha_inicio=request.POST['fecha_inicio'],
          fecha_conclucion=request.POST['fecha_conclucion'],
          nombre_etapa=request.POST['nombre_etapa'],
          avance=request.POST['avance'],
          dias=request.POST['dias'],
          observaciones=request.POST['observaciones'],
          informe=request.POST['informe'],
          proyecto=Proyectos.objects.get(id=pk))

        etapa.save()
        print 'llegoooo aaaaquiiii'
        data = {'pk': etapa.pk, 'fecha_inicio': etapa.fecha_inicio, 'fecha_conclucion': etapa.fecha_conclucion, 'nombre_etapa': etapa.nombre_etapa, 'avance': etapa.avance, 'dias': etapa.dias, 'observaciones': etapa.observaciones, 'informe': etapa.informe}
        print 'guardoooooooo'
        return HttpResponse(json.dumps(data), content_type='application/json')
    else:
        variables = RequestContext(request, {'pk': pk, 'proyecto': Proyectos.objects.get(id=pk)})
        return render_to_response('planificacion/crear_etapa.html', variables)


def listaEtapas(request, pk):
    etapas = Etapas.objects.filter(proyecto=pk)
    data = []
    for etapa in etapas:
        data.append({'pk': etapa.pk, 'fecha_inicio': etapa.fecha_inicio, 'fecha_conclucion': etapa.fecha_conclucion, 'nombre_etapa': etapa.nombre_etapa, 'avance': etapa.avance, 'dias': etapa.dias, 'observaciones': etapa.observaciones, 'informe': etapa.informe, 'responsable': etapa.proyecto.responsable_proyecto.username, 'seguimiento': etapa.proyecto.responsable_seguimiento, 'proyecto': etapa.proyecto.nombre_proyecto})

    json_data = json.dumps(data, cls=DjangoJSONEncoder)
    return HttpResponse(json_data, content_type="application/json")


# Create your views here.
def ReporteGantt(request, pk):
    proyecto = Proyectos.objects.get(pk=pk)
    variables = RequestContext(request, {'pk': pk, 'nombre_proyecto': proyecto.nombre_proyecto})
    return render_to_response('planificacion/reporte_gantt.html', variables)


def GanttAjax(request, pk):
    etapas = Etapas.objects.filter(proyecto=pk)
    data = []
    id_count = 0
    for etapa in etapas:
        id_count = id_count + 1
        print id_count
        p = 20 / 3
        progreso = float(etapa.avance) / float(100)
        fecha = datetime.datetime.strptime(str(etapa.fecha_inicio), '%Y-%m-%d').strftime("%d-%m-%Y")
        print progreso
        data.append({'id': id_count, 'text': etapa.nombre_etapa, 'start_date': fecha, 'duration': etapa.dias, 'order': 20, 'progress': progreso, 'parent': 0})

    json_data = json.dumps(data, cls=DjangoJSONEncoder)
    return HttpResponse(json_data, content_type="application/json")


def eliminarProyecto(request, id):
    p = Proyectos.objects.get(id=id)
    p.delete()
    return HttpResponseRedirect(reverse_lazy('lista_proyectos'))


class EditProyecto(UpdateView):
    template_name = "planificacion/edit_proyecto.html"
    model = Proyectos
    fields = ['region', 'municipio', 'nombre_proyecto', 'responsable_proyecto', 'responsable_seguimiento', 'fecha_inicio', 'fecha_conclucion']
    success_url = reverse_lazy('lista_proyectos')

    def get_form(self, form_class):
        form = super(EditProyecto, self).get_form(form_class)
        form.fields['fecha_inicio'].widget = forms.DateInput(format='%Y-%m-%d')
        form.fields['fecha_conclucion'].widget = forms.DateInput(format='%Y-%m-%d')
        return form
        

# Create your views here.
def listaInspeccion(request, pk):
    etapa = Etapas.objects.get(pk=pk)
    inspecciones = Inspeccion.objects.filter(etapa=pk)
    print time.strftime("%X")

    variables = RequestContext(request, {'pk': pk, 'etapa': etapa.nombre_etapa, 'proyecto': etapa.proyecto.nombre_proyecto,  'inspecciones': inspecciones})

    return render_to_response('planificacion/lista_inspeccion.html', variables)


def listaInspeccionAjax(request, pk):
    inspecciones = Inspeccion.objects.filter(etapa=pk)
    data = []
    for ins in inspecciones:
        data.append({'pk': ins.pk, 'fecha': ins.fecha, 'hora': ins.hora, 'objetivo': ins.objectivo, 'avance': ins.avance})

    json_data = json.dumps(data, cls=DjangoJSONEncoder)
    return HttpResponse(json_data, content_type="application/json")


def CrearInspeccion(request, pk):
    if request.method == 'POST':
        form = inspeccionForm(request.POST)
        if form.is_valid():
            inspeccion = Inspeccion(
                fecha=datetime.date.today(),
                hora=datetime.datetime.today().time(),
                objectivo=form.cleaned_data['objetivo'],
                avance=form.cleaned_data['avance'],
                etapa=Etapas.objects.get(pk=pk))

            inspeccion.save()
            etapa = Etapas.objects.filter(pk=pk)
            etapa.update(avance=inspeccion.avance)
            return HttpResponseRedirect(reverse_lazy('lista_inspeccion', kwargs={'pk':pk}))
    else:
        form = inspeccionForm()
    variables = RequestContext(request, {'form': form})

    return render_to_response('planificacion/crear_inspeccion.html', variables)


def eliminarInspeccion(request, id):

templates/planificacion/crear_planificacion.html
{% extends "base.html" %}
{% block contenido %}
{% load widget_tweaks %}


<div class="right_col" role="main">
          <div class="">
            <div class="page-title">
              <div class="title_left">
                <h3>Registro Proyecto</h3>
              </div>         
            </div>
            <div class="clearfix"></div>
            <div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                
                  <div class="x_content">
                    <br />
                    <form id="demo-form2" data-parsley-validate class="form-horizontal form-label-left" method="post">
						{% csrf_token %}
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Region<span class="required"></span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          
                          {{form.regiones|add_class:" form-control col-md-7 col-xs-12"|add_error_class:"parsley-error"}}
                          {% if form.errors.regiones %}
	                          <ul id="parsley-id-5" class="parsley-errors-list filled">
	                          	<li class="parsley-required">{{form.errors.regiones|removetags:'ul li'}}</li>
	                          </ul>
	                       {% endif %}

                        </div>
                      </div>

                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Municipio<span class="required"></span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          
                          <select class="form-control col-md-7 col-xs-12 {% if form.errors.municipios %}parsley-error{% endif %}" id="id_municipios" name="municipios">
                            <option value="">Seelecione el municipio</option>
                          </select>
                          {% if form.errors.municipios %}
                            <ul id="parsley-id-5" class="parsley-errors-list filled">
                              <li class="parsley-required">{{form.errors.municipios|removetags:'ul li'}}</li>
                            </ul>
                         {% endif %}

                        </div>
                      </div>

                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Nombre Proyecto<span class="required"></span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          {{form.nombre_proyecto|add_class:"form-control col-md-7 col-xs-12"|add_error_class:"parsley-error"}}
                          {% if form.errors.nombre_proyecto %}
                            <ul id="parsley-id-5" class="parsley-errors-list filled">
                              <li class="parsley-required">{{form.errors.nombre_proyecto|removetags:'ul li'}}</li>
                            </ul>
                         {% endif %}

                        </div>
                      </div>

                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Responsable Proyecto<span class="required"></span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          {{form.responsable_proyecto|add_class:"form-control col-md-7 col-xs-12"|add_error_class:"parsley-error"}}
                          {% if form.errors.responsable_proyecto %}
                            <ul id="parsley-id-5" class="parsley-errors-list filled">
                              <li class="parsley-required">{{form.errors.responsable_proyecto|removetags:'ul li'}}</li>
                            </ul>
                         {% endif %}

                        </div>
                      </div>

                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Responsable Seguimiento<span class="required"></span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          {{form.responsable_seguimiento|add_class:"form-control col-md-7 col-xs-12"|add_error_class:"parsley-error"}}
                          {% if form.errors.responsable_seguimiento %}
                            <ul id="parsley-id-5" class="parsley-errors-list filled">
                              <li class="parsley-required">{{form.errors.responsable_seguimiento|removetags:'ul li'}}</li>
                            </ul>
                         {% endif %}

                        </div>
                      </div>

                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Fecha de Inicio<span class="required"></span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          
                          {{form.fecha_inicio|add_class:"date-picker form-control col-md-7 col-xs-12"|add_error_class:"parsley-error"}}
                          {% if form.errors.fecha_inicio %}
                            <ul id="parsley-id-5" class="parsley-errors-list filled">
                              <li class="parsley-required">{{form.errors.fecha_inicio|removetags:'ul li'}}</li>
                            </ul>
                         {% endif %}

                        </div>
                      </div>

                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Fecha de Conclucion<span class="required"></span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          
                          {{form.fecha_conclucion|add_class:"date-picker form-control col-md-7 col-xs-12"|add_error_class:"parsley-error"}}
                          {% if form.errors.fecha_conclucion %}
                            <ul id="parsley-id-5" class="parsley-errors-list filled">
                              <li class="parsley-required">{{form.errors.fecha_conclucion|removetags:'ul li'}}</li>
                            </ul>
                         {% endif %}

                        </div>
                      </div>

                      <div class="ln_solid"></div>
                      <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                          <button type="submit" class="btn btn-primary">Cancelar</button>
                          <button type="submit" class="btn btn-success">Guardar</button>
                        </div>
                      </div>

                    </form>
                  </div>
                </div>
              </div>
            </div>

           

         



           
          </div>
        </div>


{% endblock %}
{% block js %}
	<script>
      
        


         $('#id_fecha_inicio').daterangepicker({
          singleDatePicker: true,
          calender_style: "picker_4",
          locale: {
            format: 'YYYY-MM-DD'
          }
        }, function(start, end, label) {
          console.log(start.toISOString(), end.toISOString(), label);
        });

        $('#id_fecha_conclucion').daterangepicker({
          singleDatePicker: true,
          calender_style: "picker_4",
          locale: {
            format: 'YYYY-MM-DD'
          }
        }, function(start, end, label) {
          console.log(start.toISOString(), end.toISOString(), label);
        });

        // if ($("#id_regiones").val() == ''){
          
        //   var options = $(this).data('options', $('#id_municipios option').clone());
        //   $('#id_municipios').html(options);
        // }else{
        //   alert('sss');
        // }

        // $("#id_municipios").hide();

        // $("#id_regiones").change(function() {
        //   if ($(this).data('options') == undefined) {
        //     /*Taking an array of all options-2 and kind of embedding it on the select1*/
        //     $(this).data('options', $('#id_municipios option').clone());
            
        //   }
        //   var id = $(this).val();
        //   var options = $(this).data('options').filter('[value=' + id + ']');
        //   $('#id_municipios').html(options);
        // });


        var Metropolitana = [
          {display: "Cochabamba", value: "cochabamba"},
          {display: "Colcapirhua", value: "Colcapirhua"},
          {display: "Quillacollo", value: "Quillacollo"},
          {display: "Sacaba", value: "Sacaba"},
          {display: "Sipe Sipe", value: "Sipe Sipe"},
          {display: "Vinto", value: "Vinto"}];

        var Vallez = [
          {display:"Punata", value:"Punata"},
          {display:"Capinota", value:"Capinota"},
          {display:"Santivañes", value:"Santivañes"},
          {display:"Arani", value:"Arani"},
          {display:"Villa Rivero", value:"Villa Rivero"},
          {display:"Cliza", value:"Cliza"},
          {display:"Toco", value:"Toco"},
          {display:"Tolata", value:"Tolata"},
          {display:"Tarata", value:"Tarata"},
          {display:"Anzaldo", value:"Anzaldo"},
          {display:"Sacabamba", value:"Sacabamba"},
          {display:"Arbieto", value:"Arbieto"},
          {display:"Tacahi", value:"Tacahi"},
          {display:"Villa Gualberto Villarroel", value:"Villa Gualberto Villarroel"},
          {display:"San Benito", value:"San Benito"}];

          var Tropico = [
          {display:"Entre Rios", value:"Entre Rios"},
          {display:"Shinahota", value:"Shinahota"},
          {display:"Colomi", value:"Colomi"},
          {display:"Puerto Villarroel", value:"Puerto Villarroel"},
          {display:"Villa Tunari", value:"Villa Tunari"},
          {display:"Chimore", value:"Chimore"}];

          var Conosur = [
          {display:"Vacas", value:"Vacas"},
          {display:"Tiraque", value:"Tiraque"},
          {display:"Alalay", value:"Alalay"},
          {display:"Mizque", value:"Mizque"},
          {display:"Aiquile", value:"Aiquile"},
          {display:"Vila Vila", value:"Vila Vila"},
          {display:"Pojo", value:"Pojo"},
          {display:"Omereque", value:"Omereque"},
          {display:"Totora", value:"Totora"},
          {display:"Pocona", value:"Pocona"},
          {display:"Pasorapa", value:"Pasorapa"}];

           var Andina = [
          {display:"Bolivar", value:"Bolivar"},
          {display:"Cocapata", value:"Cocapata"},
          {display:"independencia", value:"independencia"},
          {display:"Morochata", value:"Morochata"},
          {display:"Tapacari", value:"Tapacari"},
          {display:"Tacopaya", value:"Tacopaya"},
          {display:"Sicaya", value:"Sicaya"},
          {display:"Arque", value:"Arque"}];
         
        
            //If parent option is changed
        $("#id_regiones").change(function() {
                var parent = $(this).val(); //get option value from parent 

                switch(parent){ //using switch compare selected option and populate child
                        case '1':
                        list(Metropolitana);
                        break;  
                        case '2':
                        list(Vallez);
                        break;
                        case '3':
                        list(Tropico);
                        break;
                        case '4':
                        list(Conosur);
                        break;
                        case '5':
                        list(Andina);
                        break;
                    default: //default child option is blank
                        $("#id_municipios").html('');  
                        break;
                }
          });
          //function to populate child select box
          function list(array_list){
               //reset child options
               $("#id_municipios").html(""); 
              $(array_list).each(function (i) { //populate child options 
                  console.log(i);
         

              $("#id_municipios").append("<option value=\""+array_list[i].value+"\">"+array_list[i].display+"</option>");
             

              });
          }
        



    </script>
{% endblock js %}

templates/planificacion/listado_responsables.html
{% extends "base.html" %}
{% block contenido %}
  <!-- page content -->
        <div class="right_col" role="main">
          <div class="">
            <div class="page-title">
              

              <div class="title_right">
                <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                  <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search for...">
                    <span class="input-group-btn">
                      <button class="btn btn-default" type="button">Go!</button>
                    </span>
                  </div>
                </div>
              </div>
            </div>

            <div class="clearfix"></div>

            <div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    
                  <div class="x_content">
                    
                    <table id="datatable" class="table table-striped table-bordered">
                      <thead>
                        <tr>
                          <th>NOM_RESPONSABLES</th>
                          <th>COD_RESPONSABLES</th>
                          <th>CI_RESPONSABLES</th>
                          <th>TELEFONO_RESPONSABLES</th>
                          <th>DIRECION_RESPONSABLES</th>
                        </tr>
                      </thead>


                      <tbody>
                        
                        {% for responsables in object_list %}

                        {# #esto es para que registre #}
                            <tr>
                              
                              <td>{{ responsables.nombre}}</td>
                              <td>{{ responsables.codido}}</td>
                              <td>{{ responsables.ci}}</td>
                              <td>{{ responsables.telefono}}</td>
                              <td>{{ responsables.direccion}}</td>
          
                              
                            </tr>

                        {% endfor %}
                        
                   
                        
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>

            </div>
          </div>
        </div>
        <!-- /page content -->
{% endblock %}